[package]
name = "cssparser"
version = "0.0.0"

authors = ["Your Name <your@email.com>"]
tags = []

[[lib]]
name = "cssparser"

[[bin]]
name = "rust-less"

[dependencies.encoding]
git = "https://github.com/lifthrasiir/rust-encoding.git"
